## PostgreSQL
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/helenos
    username: helenos
    password: helenos

# eureka server url
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
helenos:
  stripeKey: sk_test_fgHWq5be8y7YV3dAHsxe6zSi003gqJ6kRw