version: "2"

services:

  nginx:
    container_name: nginx-helenos
    image: nginx-helenos
    build:
     context: .
     dockerfile:  nginx.test.dockerfile
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    external:
      name: helenos-network