version: "2"

services:

  nginx:
    container_name: nginx-helenos
    image: nginx-helenos
    build:
     context: .
     dockerfile:  nginx.prod.dockerfile
    volumes:
      - /home/vetter_leo/certbot/conf:/etc/letsencrypt
      - /home/vetter_leo/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /home/vetter_leo/certbot/conf:/etc/letsencrypt
      - /home/vetter_leo/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  default:
    external:
      name: helenos-network