## PostgreSQL
spring:
  application:
    name: zuul-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres/helenos
    username: helenos
    password: helenos
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql:  false
    hibernate:
      ddl-auto: none

eureka:
  instance:
    hostname: tomcat-zuul-server
  client:
    serviceUrl:
      defaultZone: http://tomcat-eureka-server:8761/eureka/

helenos:
  host: 165.22.72.253