## PostgreSQL
spring:
  application:
    name: zuul-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/helenos
    username: helenos
    password: helenos
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql:  false
    hibernate:
      ddl-auto: none
    
    
eureka:
  instance:
    hostname: 185.146.20.149
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

helenos:
  host: 185.146.20.149