spring:
  application:
    name: file-service
  devtools:
    restart:
      enabled: true
  profiles:
    active: @activatedProperties@
  servlet:
    multipart:
      maxFileSize: 5GB
      maxRequestSize: 5GB
      max-file-size: 5GB
      max-request-size: 5GB
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

#Application properties
helenos:
  mediaLocation: src/main/resources/assets/custom/medias

# port
server:
  address: 0.0.0.0
  port: 8205