version: "3.5"

services:

  tomcat-zuul-server:
    container_name: tomcat-zuul-server
    image: tomcat-zuul-server
    build:
      context: .
      dockerfile: tomcat-zuul.prod.dockerfile
    volumes:
      - /home/vetter_leo/certbot/ssl:/usr/local/tomcat/ssl
    ports:
      - "8762:8762"

networks:
  default:
    external:
      name: helenos-network