spring:
  application:
    name: backend
  devtools:
    restart:
      enabled: true
  profiles:
    active: @activatedProperties@
  servlet:
    multipart:
      maxFileSize: 5GB
      maxRequestSize: 5GB
      max-file-size: 5GB
      max-request-size: 5GB
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  
helenos:
  mediaLocation: src/main/resources/assets/custom/medias
  sengrid-api-key: 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
  public-key-path: key.public
  private-key-path: key.private